### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by rr44** [rr44/awesome-go#1]

**Comment by rr44** [comment]
@theCoolkal
you can talk to me here, please don't cluster up that important thread.

**Comment by rr44** [comment]
@theCoolkal
Talk to me here not on that issue!

**Comment by theCoolkal** [comment]
Oh I didn't see that.  So are you not on Freenode or anything?

**Comment by rr44** [comment]
No, i'm here.

**Comment by theCoolkal** [comment]
But this is public chat

**Comment by rr44** [comment]
#tox on QuakeNet

**Comment by rr44** [comment]
@stal888

Why didn't you abandon Tox already?
